import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const exportLeaderboardToPDF = (
    leaderboard: { name: string; score: number; puzzleScore?: number }[],
    topic: string,
    roomId: string
) => {
    const doc = new jsPDF();

    // Add title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Study Room Leaderboard', 105, 20, { align: 'center' });

    // Add room info
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Topic: ${topic}`, 20, 35);
    doc.text(`Room ID: ${roomId}`, 20, 42);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 49);
    doc.text(`Time: ${new Date().toLocaleTimeString()}`, 20, 56);

    // Add leaderboard table
    const tableData = leaderboard.map((entry, index) => {
        const puzzleScore = entry.puzzleScore || 0;
        const totalScore = entry.score + puzzleScore;
        return [
            index + 1,
            entry.name,
            entry.score,
            puzzleScore,
            totalScore,
            index === 0 ? '🥇' : index === 1 ? '🥈' : index === 2 ? '🥉' : ''
        ];
    });

    autoTable(doc, {
        startY: 65,
        head: [['Rank', 'Name', 'Quiz', 'Puzzle', 'Total', 'Medal']],
        body: tableData,
        theme: 'striped',
        headStyles: {
            fillColor: [59, 130, 246], // Blue
            fontSize: 12,
            fontStyle: 'bold'
        },
        styles: {
            fontSize: 11,
            cellPadding: 5
        },
        columnStyles: {
            0: { halign: 'center', cellWidth: 20 },
            1: { cellWidth: 60 },
            2: { halign: 'center', cellWidth: 25 },
            3: { halign: 'center', cellWidth: 25 },
            4: { halign: 'center', cellWidth: 25 },
            5: { halign: 'center', cellWidth: 25 }
        }
    });

    // Add footer
    const pageCount = doc.getNumberOfPages();
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text(
        `Generated by EdTech Study Room - Page ${pageCount}`,
        105,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
    );

    // Save the PDF
    const fileName = `Leaderboard_${roomId}_${new Date().getTime()}.pdf`;
    doc.save(fileName);
};
